### ISSUE TITLE
Cannot locate symbol "zsys_handler_set" referenced by "libzyrejni.so"...

### ISSUE THREAD

**Issue by vimal-gsv** [zeromq/zyre#390]
I am trying to load https://github.com/zeromq/zyre/releases/download/v1.1.0/zyre-android.jar.zip in a simple hello world android project, i get below error while running the app

[load error.txt](https://github.com/zeromq/zyre/files/79066/load.error.txt)

**Comment by hintjens** [comment]
I will write a test app tomorrow. In the meantime, can you try loading the necessary libraries in your Java code? (I can automate this if it's the correct solution):

System.loadLibrary ("czmq");
System.loadLibrary ("zmq");
System.loadLibrary ("sodium");

**Comment by sphaero** [comment]
Almost:
````
01-06 15:43:28.271 6342-6342/org.z25.zyretest D/AndroidRuntime: Shutting down VM
01-06 15:43:28.309 6342-6342/org.z25.zyretest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: org.z25.zyretest, PID: 6342
                                                                java.lang.UnsatisfiedLinkError: dlopen failed: library "libgnustl_shared.so" not found
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                    at java.lang.System.loadLibrary(System.java:1076)
                                                                    at org.z25.zyretest.ZyreTest.onCreate(ZyreTest.java:16)
                                                                    at android.app.Activity.performCreate(Activity.java:6237)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hintjens** [comment]
OK, so I think I need to package libgnustl_shared.so with the jar file.
(Or, possibly there's an option to package it in the APK).

**Comment by sphaero** [comment]
I've been searching but as far as I find you need to package this indeed.

**Comment by hintjens** [comment]
OK, new jar file here: https://github.com/zeromq/zyre/releases/tag/untagged-e9637f95978c0ba52924

**Comment by hintjens** [comment]
New jar file is here: https://github.com/zeromq/zyre/releases/tag/v1.1.0

**Comment by sphaero** [comment]
weird, it's even worse :(
```
01-06 16:23:48.252 8786-8786/org.z25.zyretest I/art: Not late-enabling -Xcheck:jni (already on)
01-06 16:23:48.283 8786-8786/org.z25.zyretest I/art: Late-enabling JIT
01-06 16:23:48.692 8786-8786/org.z25.zyretest I/art: JIT created with code_cache_capacity=2MB compile_threshold=1000
01-06 16:23:49.835 8786-8793/org.z25.zyretest W/art: Suspending all threads took: 39.296ms
01-06 16:23:50.313 8786-8793/org.z25.zyretest W/art: Suspending all threads took: 37.673ms
01-06 16:23:51.294 8786-8793/org.z25.zyretest W/art: Suspending all threads took: 10.485ms
01-06 16:23:51.479 8786-8786/org.z25.zyretest W/linker: /data/app/org.z25.zyretest-2/lib/arm/libczmq.so: unused DT entry: type 0x1d arg 0x3f23
01-06 16:23:51.504 8786-8786/org.z25.zyretest W/linker: /data/app/org.z25.zyretest-2/lib/arm/libzmq.so: unused DT entry: type 0x1d arg 0xabbc
01-06 16:23:51.758 8786-8786/org.z25.zyretest D/AndroidRuntime: Shutting down VM
01-06 16:23:51.770 8786-8786/org.z25.zyretest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: org.z25.zyretest, PID: 8786
                                                                java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "zsys_handler_set" referenced by "/data/app/org.z25.zyretest-2/lib/arm/libzyrejni.so"...
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                    at java.lang.System.loadLibrary(System.java:1076)
                                                                    at org.zeromq.zyre.Zyre.<clinit>(Zyre.java:13)
                                                                    at org.z25.zyretest.ZyreTest.onCreate(ZyreTest.java:19)
                                                                    at android.app.Activity.performCreate(Activity.java:6237)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-06 16:24:08.483 8786-8793/org.z25.zyretest W/art: Suspending all threads took: 66.928ms
01-06 16:24:21.508 8786-8786/org.z25.zyretest I/Process: Sending signal. PID: 8786 SIG: 9
```
And this is with the 
```
System.loadLibrary ("czmq");
System.loadLibrary ("zmq");
System.loadLibrary ("sodium");
```
calls

**Comment by hintjens** [comment]
OK, I'm biting the bullet and trying my own test app.

**Comment by sphaero** [comment]
If you want to know what I did:
* Install Android Studio
* Install extra stuff through SDK manager (Emulator & images)
* Create New Project, with empty activity
* copy zyre-android.jar to the app/libs dir
* Add zyre-android.jar as a File dependency through File - Project Structure
* Add the code
* Run on a emulator (painfully slow)

Code:
```
package org.z25.zyretest;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import org.zeromq.zyre.Zyre;

public class ZyreTest extends AppCompatActivity {

    public Zyre znode;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_zyre_test);
        System.loadLibrary ("czmq");
        System.loadLibrary ("zmq");
        System.loadLibrary ("sodium");
        znode = new Zyre("AndroidTest");
        znode.start();
    }

    @Override
    public void onDestroy()
    {
        super.onDestroy();
        znode.stop();
    }
}
```

**Comment by hintjens** [comment]
That was helpful, @sphaero, thanks. /waits for emulator to boot...

**Comment by vimalgsv** [comment]
From czmq already contains zsys_handler_set
readelf libczmq.so -a | grep zsys_handler_set
   791: 000598c8   256 FUNC    GLOBAL DEFAULT    8 zsys_handler_set
  3853: 000598c8   256 FUNC    GLOBAL DEFAULT    8 zsys_handler_set

when i tried to check the linker options in zyrejni.so

vnd2kor@pitt:~/share$ readelf libzyrejni.so -a | grep Shared
  Type:                              DYN (Shared object file)
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]

where as libzyre shoes it has libczmq

vnd2kor@pitt:~/share$ readelf libzyre.so -a | grep Shared
  Type:                              DYN (Shared object file)
 0x00000001 (NEEDED)                     Shared library: [libczmq.so]
 0x00000001 (NEEDED)                     Shared library: [libsodium.so]
 0x00000001 (NEEDED)                     Shared library: [libzmq.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libgnustl_shared.so]

is this problem with how zyrejni is linked?

**Comment by hintjens** [comment]
Ah, this looks like the right track. :)

**Comment by hintjens** [comment]
@vimal-gsv, do you have the original build.gradle used for building this .so?

**Comment by hintjens** [comment]
@vimal-gsv this was I think the problem. The Zyre test is now failing with another error,

```
zsys: (UDP) error 'Permission denied' on socket
src/zsys.c:987: zsys_socket_error: assertion "false" failed
Fatal signal 6 (SIGABRT), code -6 in tid 13354 (imatix.zyretest)
```

Which I'll make an issue for.
