### ISSUE TITLE
Use of Zyre 2.0.1 in Android

### ISSUE THREAD

**Issue by Katawann** [zeromq/zyre#688]
Hello,

I try to implement Zyre into an Android app (emulator Pixel_3a_API_30_x86) but without any success so far... I downloaded the `zyre-android-all-2.0.1.jar` and added the jar file like proposed [here](https://stackoverflow.com/a/35241990). 

The app is just an empty activity with two Zyre instances (based on [Java example](https://github.com/zeromq/zyre/tree/master/examples/jni/src/main/java/org/zyre/helloworld))
```
package com.test.zyresandbox;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import org.zeromq.czmq.Zmsg;
import org.zeromq.zyre.Zyre;
import org.zeromq.zyre.ZyreEvent;

public class MainActivity extends AppCompatActivity {

    private Zyre peer1 = new Zyre("peer1");
    private Zyre peer2 = new Zyre("peer2");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
```

but it fails on start because it seems that it does not find the library:

```
2021-02-02 18:06:55.345 8095-8095/com.test.zyresandbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.zyresandbox, PID: 8095
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/scijava/nativelib/NativeLoader;
        at org.zeromq.tools.ZmqNativeLoader.loadLibrary(ZmqNativeLoader.java:123)
        at org.zeromq.tools.ZmqNativeLoader.loadLibraries(ZmqNativeLoader.java:115)
        at org.zeromq.zyre.Zyre.<clinit>(Zyre.java:22)
        at com.test.zyresandbox.MainActivity.<init>(MainActivity.java:13)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.scijava.nativelib.NativeLoader" on path: DexPathList[[zip file "/data/app/~~gy941gwKTSZ5YO1nt981mg==/com.test.zyresandbox-mUFKmzXJfRO_71gwsAfAOw==/base.apk"],nativeLibraryDirectories=[/data/app/~~gy941gwKTSZ5YO1nt981mg==/com.test.zyresandbox-mUFKmzXJfRO_71gwsAfAOw==/lib/x86, /data/app/~~gy941gwKTSZ5YO1nt981mg==/com.test.zyresandbox-mUFKmzXJfRO_71gwsAfAOw==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.zeromq.tools.ZmqNativeLoader.loadLibrary(ZmqNativeLoader.java:123) 
        at org.zeromq.tools.ZmqNativeLoader.loadLibraries(ZmqNativeLoader.java:115) 
        at org.zeromq.zyre.Zyre.<clinit>(Zyre.java:22) 
        at com.test.zyresandbox.MainActivity.<init>(MainActivity.java:13) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-02-02 18:06:55.350 8095-8137/com.test.zyresandbox D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
2021-02-02 18:06:55.434 8095-8095/com.test.zyresandbox I/Process: Sending signal. PID: 8095 SIG: 9

```

Does anyone already integrate Zyre in Android and could help me to integrate Zyre properly ?

**Comment by sappo** [comment]
Include https://github.com/scijava/native-lib-loader as dependency.

Quentin Collet <notifications@github.com> schrieb am Di., 2. Feb. 2021,
18:12:

**Comment by Katawann** [comment]
Thank you ! It fixes that issue by adding the following line:
```
dependencies {

        ...

    implementation 'org.scijava:native-lib-loader:2.3.5'

        ...

}
```

now I move to another issue when I try:
```
// SHOUT message - Message is send to all peers in group 'CHAT'
Zmsg msgToSend = new Zmsg();
msgToSend.addstr("Hello Mate!");
peer1.shout("CHAT", msgToSend);
```
with error:
```
W/System.err: [WARN] Couldn't load library library uuid from jar. Assuming it is installed on the system.
W/System.err: [WARN] Couldn't load library library libsystemd from jar. Assuming it is installed on the system.
E/linker: library "/system/lib/liblz4.so" ("/system/lib/liblz4.so") needed or dlopened by "/apex/com.android.art/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/~~xOC1__5rI-zNz3pPH_iN7A==/com.test.zyresandbox-ECJoPE-su3j0CMyFMlvvAg==/lib/x86:/data/app/~~xOC1__5rI-zNz3pPH_iN7A==/com.test.zyresandbox-ECJoPE-su3j0CMyFMlvvAg==/base.apk!/lib/x86", permitted_paths="/data:/mnt/expand:/data/user/0/com.test.zyresandbox"]
W/System.err: [WARN] Couldn't load library library lz4 from jar. Assuming it is installed on the system.
E/linker: library "/system/lib/libcurl.so" ("/system/lib/libcurl.so") needed or dlopened by "/apex/com.android.art/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/~~xOC1__5rI-zNz3pPH_iN7A==/com.test.zyresandbox-ECJoPE-su3j0CMyFMlvvAg==/lib/x86:/data/app/~~xOC1__5rI-zNz3pPH_iN7A==/com.test.zyresandbox-ECJoPE-su3j0CMyFMlvvAg==/base.apk!/lib/x86", permitted_paths="/data:/mnt/expand:/data/user/0/com.test.zyresandbox"]
W/System.err: [WARN] Couldn't load library library curl from jar. Assuming it is installed on the system.
W/System.err: [WARN] Couldn't load library library nss from jar. Assuming it is installed on the system.
W/System.err: [WARN] Couldn't load library library microhttpd from jar. Assuming it is installed on the system.
```

By the way, I think it would be nice to have the information you are providing me in the documentation. I will try to add it if I succeed with the integration of Zyre
